baseURL = "/"
languageCode = "en"
title = "Tom Wilks - Web Developer from Manchester"
theme = "wilks"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = -110
  [[menu.main]]
		identifier = "articles"
    name = "Articles"
    url = "/articles"
    weight = -100
