baseURL = "https://wilks.co"
languageCode = "en"
description = "Tom Wilks is a Manchester based front-end web developer specialising in Drupal and modern web technologies."
theme = "wilks"
[params]
  Title = "Tom Wilks - Front-end Web Developer from Manchester"
  Description = "Tom Wilks is a Manchester based front-end web developer specialising in Drupal and modern web technologies."
  theme = ""
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = -110
  [[menu.main]]
		identifier = "work"
    name = "Work"
    url = "/work"
    weight = -100
  [[menu.main]]
		identifier = "articles"
    name = "Articles"
    url = "/articles"
    weight = -90
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "monokai"
    tabWidth = 2