options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
  ignore: 'static/css/src/vendors/**/*.scss'
rules:
  # Extends
  extends-before-mixins: 0
  extends-before-declarations: 0
  placeholder-in-extend: 0
  no-extends: 2

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-ids: 1
  no-important: 1
  no-invalid-hex: 0
  no-mergeable-selectors: 0
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-zero: 0
  no-transition-all: 0
  no-url-protocols: 1
  no-vendor-prefixes: 1
  no-warn: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  function-name-format: 0
  mixin-name-format: 0
  placeholder-name-format: 0
  variable-name-format: 1
  pseudo-element: 0
  class-name-format:
    - 1
    - convention: hyphenatedbem
    - allow-leading-underscore: true

  # Style Guide
  border-zero: 0
  brace-style:
    - 1
    - allow-single-line: false
  clean-import-paths: 0
  empty-args: 0
  hex-length: 0
  hex-notation: 0
  indentation: 2
  leading-zero: 0
  nesting-depth: 1
  property-sort-order: 0
  quotes:
    - 1
    - style: double
  shorthand-values: 0
  url-quotes: 1
  variable-for-property: 0
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 0
  space-before-colon: 0
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 0
  space-after-bang: 0
  space-between-parens: 0

  # Final Items
  trailing-semicolon: 2
  final-newline: 0
